### PR TITLE
Allow setting class on blocker

### PR DESCRIPTION
**Pull request by sbussetti**
I want to be able to differentiate blockers for different instances, so I need a way to just set a class identifier.

### CODE REVIEW

**Comment by sbussetti** [comment]
@kylefox lmk if you have any thoughts on this, thanks!

**Comment by kylefox** [comment]
Seems reasonable. If you can update the documentation I think this could be merged in.

https://github.com/kylefox/jquery-modal#tips-for-developmentcontributing

**Comment by sbussetti** [comment]
@kylefox done and done

**Comment by kylefox** [comment]
Thanks! I had to [manually merge](https://github.com/kylefox/jquery-modal/commit/2428d64cdf50f0f862b2c914efd019e18c94c924) because of a conflict (my fault).

**Pull request closed without merging**
