### PR TITLE
Support top,left argument

### PR DESCRIPTION
**Pull request by nguyenvanduocit**
Support top, left arguments

### CODE REVIEW

**Comment by samizzo** [comment]
It would be great to have this merged in!

**Comment by kylefox** [comment]
Looks cool. Before I merge, please:

- [ ] Update `README.md` to include documentation on how the new settings are to be used
- [ ] Add an example to `examples/index.html`
- [ ] Rename `.positioning()` to `.position()` (method names should be verbs)

Thanks!

**Comment by nguyenvanduocit** [comment]
ok, I will update it sooon

**Comment by nguyenvanduocit** [comment]
Please review my commits. Let me know if I need to do anything else.

**Comment by kylefox** [comment]
Thanks, looks good. However I realized it may conflict with #110 which moved positioning the modal to pure CSS. I'll have a closer look sometime in the next few days and see what's best.

**Comment by nguyenvanduocit** [comment]
Thanks, I will follow this conversation.

**Pull request closed without merging**
