### PR TITLE
feat: New global event listener $.modal.ALL. Fixes #282

### LINKED ISSUE #282: Is there something like 'CATCH-ALL' for the events?
Currently I am catching the events with this:

```
            $(<selector>).on(
                $.modal.BEFORE_OPEN + ' ' +
                $.modal.OPEN + ' ' +
                $.modal.AFTER_CLOSE,
                function (e) {
                        window[functionName](e);
                    }
                );

```

This means, it's very general as I differ in the callback function when it was called. This helps me to re-use the code and follow the DRY approach. 

Is there a way I can catch all of the existing events without calling them uniquely? Something like wildchars expression?

```javascript
$.modal.BEFORE_BLOCK = 'modal:before-block';    // Fires just before the overlay (blocker) appears.
$.modal.BLOCK = 'modal:block';                  // Fires after the overlay (block) is visible.
$.modal.BEFORE_OPEN = 'modal:before-open';      // Fires just before the modal opens.
$.modal.OPEN = 'modal:open';                    // Fires after the modal has finished opening.
$.modal.BEFORE_CLOSE = 'modal:before-close';    // Fires when the modal has been requested to close.
$.modal.CLOSE = 'modal:close';                  // Fires when the modal begins closing (including animations).
$.modal.AFTER_CLOSE = 'modal:after-close';      // Fires after the modal has fully closed (including animations).
```

### PR DESCRIPTION
**Pull request by Zenoo**
I added a new event `$.modal.ALL = 'modal:*'` which fires every time a callback is fired.

This should fix #282

### CODE REVIEW

**Comment by kylefox** [comment]
Thanks @Zenoo! As mentioned here: https://github.com/kylefox/jquery-modal/issues/282#issuecomment-865436086 I'm not sure I understand the usefulness of this feature 🤔 and would like to hear more about the use case before we merge it.

Also, it looks like there are a lot of code formatting changes (whitespace, etc.) in this pull request. I'm totally open to adding code formatting/linting to the project, but it would be better if that was introduced in a separate PR to keep the diffs clean.

**Comment by Zenoo** [comment]
My bad, my files are automatically formatted when I save them in VSCode, I'll remove the formatting them if you prefer.

**Comment by kylefox** [comment]
@Zenoo That would be great, but let's hold off on further changes until we understand why #282 is useful in the first place 😄

**Comment by kylefox** [comment]
Closing — #282 is not a useful addition to the library.

**Pull request closed without merging**
